const shoes = [
  {
    id: 1,
    brand: "4 Craft Photon Dust",
    price: "3500",
    size: "Uk:7.5 & Eur:42",
    image: "/Assets/img10.jpg",
    condition: "9.5/10",
  },
  {
    id: 2,
    brand: "Red High Track Red",
    price: "6000",
    color: "Black",
    size: "Uk:7.5 & Eur:42",
    image: "/Assets/Shoes/img4.jpg",
    condition: "9.8/10", 
  },
  {
    id: 3,
    brand: "Aj1 Heritage",
    price: "4000",
    color: "Tan",
    size: "Uk:7.5 & Eur:42",
    image: "/Assets/Shoes/img5.jpg",
    condition: "9.4/10", // Added condition
  },
  {
    id: 4,
    brand: "Blazer Jumbo",
    price: "3500",
    color: "Blue",
    size: "Uk:7.5 & Eur:42",
    image: "/Assets/Shoes/img6.jpg",
    condition: "9.7/10", // Added condition
  },
  {
    id: 5,
    brand: "Aj1 Paris",
    price: "3500",
    color: "Gray/Orange",
    size: "Uk:6.5 & Eur:40.5",
    image: "/Assets/Shoes/img7.jpg",
    condition: "9.5/10", // Added condition
  },
  {
    id: 6,
    brand: "Travis Scott",
    price: "20,000",
    color: "Navy",
    size: "Uk:7.5 & Eur:42",
    image: "/Assets/Shoes/img8.jpg",
    condition: "10/10", 
  },
  {
    id: 7,
    brand: "Dunks Sail Multi-Camo",
    price: "6000",
    color: "Black/Red",
    size: "Uk:7.5 & Eur:42",
    image: "/Assets/Shoes/img12.jpg",
    condition: "Deadstock", 
  },
  {
    id: 8,
    brand: "Air Jordan 4",
    price: "3000",
    color: "Brown",
    size: "Uk:6 & Eur:40",
    image: "/Assets/Shoes/img14.jpg",
    condition: "9.5/10", 
  },
  {
    id: 9,
    brand: "Aj4 Lightning",
    price: "12,000",
    color: "Black",
    size: "Uk:8.5 & Eur:43",
    image: "/Assets/Shoes/img15.jpg",
    condition: "9.3/10",
  },
  {
    id: 10,
    brand: "LV Virgil Beige Trainer",
    price: "16,000",
    color: "Black",
    size: "Uk:8 & Eur:42",
    image: "/Assets/Shoes/img18.jpg",
    condition: "9.6/10", 
  },
  {
    id: 11,
    brand: "Sb Dunks Purple Pigeon",
    price: "8000",
    color: "Black",
    size: "Uk:8.5 & Eur:43",
    image: "/Assets/Shoes/img19.jpg",
    condition: "9.8/10", 
  },
  {
    id: 12,
    brand: "Air Jordan 1",
    price: "4900",
    color: "Brown",
    size: "US 10",
    image: "/Assets/DSC_0124-Web.jpg",
    condition: "7/10",
  },
];

export default shoes;
